# Generated by Django 3.0.3 on 2020-02-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('level', models.IntegerField(choices=[(1, 'easy'), (2, 'medium'), (3, 'hard'), (4, 'extreme')])),
            ],
        ),
    ]
