# Generated by Django 3.0.3 on 2020-02-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_client_thetypeoffood_workday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='location',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phone',
        ),
        migrations.AddField(
            model_name='thetypeoffood',
            name='title',
            field=models.CharField(default='chineese', max_length=100),
            preserve_default=False,
        ),
    ]
